# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'MJ Azure Service Connection'
            subscriptionId: 'af20e232-826f-408d-ac54-1e573a20805f'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'rg-mjbautista'
            location: 'Southeast Asia'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.json'
            csmParametersFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.parameters.json'
            deploymentMode: 'Validation'